trigger:
  branches:
    include:
      - main
      - feature/*

resources:
  repositories:
    - repository: ci-templates
      type: github
      name: TkachenkoTymur/ci-templates
      endpoint: TkachenkoTymur      

variables:
- group: 'USERS_API_VARIABLE_GROUP'

stages:
- stage: StageID_PreBuild
  displayName: 'Pre-Build'
  jobs:
  - job: JobID_PreBuild
    steps:
    - checkout: self
    - checkout: ci-templates
    - script: |
        source $(Build.SourcesDirectory)/ci-templates/common-scripts/dockerhub.sh
        NEW_VER=$(get_docker_image_latest_version "1.0.5")
        echo "##vso[task.setvariable variable=APP_VERSION;isOutput=true]$NEW_VER"
      name: CalculateAppVersion

- stage: StageID_BuildAndTestProject
  displayName: 'Project: Build and Test'
  dependsOn: StageID_PreBuild
  jobs:
  - job: JobID_BuildAndTest
    variables:
      VERSION: $[ stageDependencies.StageID_PreBuild.JobID_PreBuild.outputs['CalculateAppVersion.APP_VERSION'] ]
    steps:
    - script: echo "Building version $(VERSION)"

- stage: StageID_BuildAndPushDockerImage
  displayName: 'Docker: Build and Push'
  dependsOn: StageID_BuildAndTestProject
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
  jobs:
  - job: JobID_BuildAndPushDockerImage
    variables:
      VER: $[ stageDependencies.StageID_PreBuild.JobID_PreBuild.outputs['CalculateAppVersion.APP_VERSION'] ]
    steps:
    - checkout: self
    
    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        containerRegistry: 'DockerHubConnection'
        repository: $(DOCKER_REPO)
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(VER)
          latest

    - script: |
        mkdir -p "$(Build.ArtifactStagingDirectory)/DockerImage"
        LAST_IMAGE_ID=$(docker images -q | head -n 1)
        docker save "$LAST_IMAGE_ID" -o "$(Build.ArtifactStagingDirectory)/DockerImage/image.tar"
      displayName: 'Save Docker image to tar'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Docker image artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/DockerImage/image.tar'
        artifact: 'DockerImage_$(VER)'

    - task: Docker@2
      displayName: 'Push Docker Image'
      inputs:
        containerRegistry: 'DockerHubConnection'
        repository: $(DOCKER_REPO)
        command: 'push'
        tags: |
          $(VER)
          latest

- stage: StageID_HelmChart
  displayName: 'Helm Chart: Pack and...'
  dependsOn: StageID_BuildAndPushDockerImage
  jobs:
  - job: JobID_HelmChart
    steps:
    - script: echo "Placeholder"

- stage: StageID_PostBuild
  displayName: 'Post-Build'
  dependsOn: StageID_HelmChart
  condition: always()
  jobs:
  - job: JobID_PostBuild
    steps:
    - script: echo "Done"