resources:
  repositories:
    - repository: ci-templates
      type: git
      name: ci-templates
      ref: refs/heads/main

variables:
  - group: USERS_API_VARIABLE_GROUP

stages:
- template: templates/stages/pre-build/v1.yaml@ci-templates
  parameters:
    [cite_start]ciTemplates: 'ci-templates' 
    dockerId: $(DOCKER_ID)
    dockerRepo: $(DOCKER_REPO)
    dockerToken: $(DOCKER_TOKEN)

# Решта шаблонів (python та docker) залишаються без змін

- template: templates/stages/python/v1.yaml@ci-templates
  parameters:
    appVersion: $[ stageDependencies.StageID_PreBuild.JobID_PreBuild.outputs['CalculateAppVersion.APP_VERSION'] ]

- template: templates/stages/docker/v1.yaml@ci-templates
  parameters:
    appVersion: $[ stageDependencies.StageID_PreBuild.JobID_PreBuild.outputs['CalculateAppVersion.APP_VERSION'] ]
    dockerId: $(DOCKER_ID)
    dockerRepo: $(DOCKER_REPO)