trigger:
  branches:
    include:
      - main
      - feature/*

resources:
  repositories:
    - repository: ci-templates
      type: github
      name: TkachenkoTymur/ci-templates
      endpoint: TkachenkoTymur      

variables:
- group: 'USERS_API_VARIABLE_GROUP'

stages:
- stage: StageID_PreBuild
  displayName: 'Pre-Build'
  jobs:
  - job: JobID_PreBuild
    displayName: 'Pre-Build Analysis'
    steps:
    - checkout: self
    - checkout: ci-templates

    - script: |
        # Тепер шлях точно буде працювати
        source $(Build.SourcesDirectory)/ci-templates/common-scripts/logging.sh
        
        info_msg "--- PREDEFINED VARIABLES ---"
        info_msg "Agent.TempDirectory: $(Agent.TempDirectory)"
        info_msg "Build.ArtifactStagingDirectory: $(Build.ArtifactStagingDirectory)"
        info_msg "Build.Repository.LocalPath: $(Build.Repository.LocalPath)"
        info_msg "Build.Repository.Name: $(Build.Repository.Name)"
        info_msg "Build.SourceBranch: $(Build.SourceBranch)"
        info_msg "Build.SourceBranchName: $(Build.SourceBranchName)"
        info_msg "Build.SourcesDirectory: $(Build.SourcesDirectory)"
        info_msg "Build.StagingDirectory: $(Build.StagingDirectory)"
      displayName: 'Predefined variables with color'

- stage: StageID_BuildAndTestProject
  displayName: 'Project: Build and Test'
  dependsOn: StageID_PreBuild
  jobs:
  - job: JobID_BuildAndTest
    displayName: 'Build and Test'
    steps:
    - script: echo "Hello, from Build And Test Job"
      displayName: 'Script'

- stage: StageID_PostBuild
  displayName: 'Post-Build'
  dependsOn: StageID_BuildAndTestProject
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: JobID_PostBuild
    displayName: 'Post-Build'
    steps:
    - script: echo "Hello, from Post-Build Job"
      displayName: 'Script'